name: "Build Langtrace CLI"
on:
  workflow_dispatch:
    inputs:
      RegistryEnv:
        type: environment
        description: "Select Env"
        required: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller
        working-directory: cli/

      - name: Build CLI for ${{ matrix.os }}
        run: pyinstaller --onefile fynetune-cli.py
        working-directory: cli/

      - name: Smoke test
        run: ./dist/fynetune-cli --version
        working-directory: cli/

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*
